### ISSUE TITLE
Error after latest update.

### ISSUE THREAD

**Issue by vawallace** [vladfrangu/async_event_emitter#2]
The package.json is looking for a .js file but the dist folder only contains .cjs

`Error: Cannot find module 'node_modules/@vladfrangu/async_event_emitter/dist/index.js'`

**Comment by thelegendtubaguy** [comment]
Can confirm that changing package.json references of `index.js` to `index.cjs` fixes this.

**Comment by OIRNOIR** [comment]
I can +1 this

**Comment by AmNotAGoose** [comment]
+1
Getting same issue here

**Comment by codysblanchard** [comment]
+1 same error

**Comment by ovap** [comment]
+1, 
@thelegendtubaguy thanks for the workaround.
